"""Constants used for interacting with the graph objects.

Generally, these are property or key names.
"""

NODE_COORDINATE_KEY = "node_coordinate"
EDGE_SPLINE_KEY = "spline"
EDGE_COORDINATES_KEY = "path"
EDGE_ID_KEY = "ID"
PARENT_EDGE_ID_KEY = "parent_ID"
START_NODE_KEY = "start_node"
END_NODE_KEY = "end_node"
MIDLINE_NODE_KEY = "midline_node"
EXE_EPC_NODE_KEY = "exe_epc_node"
GENERATION_KEY = "level"
VALIDATION_KEY = "validated"
LENGTH_KEY = "length"
NUMBER_OF_TIPS_KEY = "number_of_tips"
SISTER_EDGE_KEY = "sister_edge"
PARENT_EDGE_KEY = "parent_edge"
DAUGHTER_EDGES_KEY = "daughter_edges"
ROTATION_ANGLE_EDGE_KEY = "rotation_angle"
BRANCH_ANGLE_EDGE_KEY = "branch_angle"
BRANCH_ANGLE_JUNCTION_EDGE_KEY = "branch_angle_junction"
SIBLING_ANGLE_EDGE_KEY = "sibling_angle"
LOBE_NAME_KEY = "lobe"
SURFACE_ANGLE_EDGE_KEY = "surface_angle"
ROTATION_ANGLE_VECTOR_EDGE_KEY = "rotation_angle_parent_vector_daughter_plane"
BRANCH_CURVATURE_EDGE_KEY = "branch_curvature"
DIAMETER_KEY = "lumen_diameter"
TISSUE_THICKNESS_KEY = "tissue_thickness"
